# Generated by Django 4.1 on 2022-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
