# Generated by Django 4.1 on 2022-10-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='user',
        ),
    ]
