# Generated by Django 4.1 on 2022-10-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ft', '0004_remove_admin_ft_entry_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_ft_entry',
            name='jumlah_pohon',
        ),
        migrations.RemoveField(
            model_name='admin_ft_entry',
            name='nominal_uang',
        ),
        migrations.RemoveField(
            model_name='admin_ft_entry',
            name='pesan',
        ),
    ]
