# Generated by Django 4.1 on 2022-10-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ft', '0005_remove_admin_ft_entry_jumlah_pohon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_ft_entry',
            name='noted',
            field=models.TextField(default='-'),
        ),
    ]
