# Generated by Django 4.1.2 on 2022-11-01 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0003_remove_campaign_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pendaftar', models.CharField(default='', max_length=50)),
                ('email_pendaftar', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='0', max_length=15)),
                ('what_can_you_help_with', models.CharField(default='', max_length=50, verbose_name='What can you help with?')),
                ('reason_to_participate', models.CharField(default='', max_length=500)),
                ('campaign', models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign', to_field='title')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
