# Generated by Django 4.1 on 2022-10-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='user',
        ),
    ]
