# Generated by Django 4.1.2 on 2022-10-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='user',
        ),
    ]
