# Generated by Django 4.1 on 2022-10-31 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_title'),
        ('participate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='campaign',
            field=models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign', to_field='title'),
        ),
    ]
