# Generated by Django 4.1.2 on 2022-10-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0003_participants_what_can_you_help_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='what_can_you_help_with',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What can you help with?'),
        ),
    ]
