# Generated by Django 4.1.2 on 2022-10-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0004_alter_participants_what_can_you_help_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='reason_to_participate',
            field=models.CharField(default='', max_length=500),
        ),
    ]
