# Generated by Django 4.1.2 on 2022-10-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0005_participants_reason_to_participate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='what_can_you_help_with',
            field=models.CharField(default='', max_length=50, verbose_name='What can you help with?'),
        ),
    ]
